### ISSUE TITLE
1.0.1 release?

### ISSUE THREAD

**Issue by tuxedo0801** [cs4j/cs4j#1]
Hi,

great library. Exactly what I need. But I need the "declaredMethods"-feature, which requires Version 1.0.1, which is in SNAPSHOT phase.

Is there a release-date (with upload to maven central) planned?

br,
Alex

**Comment by mfursov** [comment]
Updated the version in maven with the latest changes. 

Please file all issues you found with this package - the package itself is quite young and I tested it by myself in 1 real project only.
